# Generated by Django 5.0.2 on 2024-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('purchase_history', models.TextField(max_length=500)),
                ('wallet', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyAccountView',
        ),
    ]
